tachi098/HHTLMilkTea

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Category.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Product.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Role.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/SaleOff.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/User.java
Add Product Category SaleOff Model
> Add Product Category SaleOff Model

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/HhtlmilkteaapiApplication.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SaleOffController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Product.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/SaleOff.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedProductsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedSaleOffsTable.java
> fix code, product, safeoff

- hhtlmilkteaapi/src/main/resources/application.properties
fix code, application.properties
> fix code, application.properties

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/HhtlmilkteaapiApplication.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/WebSecurityConfig.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/MemberVipController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Category.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/MemberVip.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IMemberVipRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedMemberVipsTable.java
> fix code, membervip

- hhtlmilkteaadmin/package.json
- hhtlmilkteaadmin/public/index.html
- hhtlmilkteaadmin/src/App.js
- hhtlmilkteaadmin/src/components/Dashboard/Chart/index.jsx
- hhtlmilkteaadmin/src/components/Dashboard/Deposits/index.jsx
- hhtlmilkteaadmin/src/components/Dashboard/Order/index.jsx
- hhtlmilkteaadmin/src/components/Dashboard/Title/index.jsx
- hhtlmilkteaadmin/src/components/Dashboard/index.jsx
- hhtlmilkteaadmin/src/components/Layout/Footer/index.jsx
- hhtlmilkteaadmin/src/components/Layout/ListItem/index.jsx
- hhtlmilkteaadmin/src/components/Layout/Navbar/index.jsx
- hhtlmilkteaadmin/src/components/Something/Form/index.jsx
- hhtlmilkteaadmin/src/components/Something/Table/index.jsx
- hhtlmilkteaadmin/src/index.js
- hhtlmilkteaadmin/yarn.lock
> add template admin

- hhtlmilkteaadmin/src/components/Spinner/index.jsx
> fix code, button add

- hhtlmilkteaadmin/package.json
- hhtlmilkteaadmin/src/App.js
- hhtlmilkteaadmin/src/common/APIClient.js
- hhtlmilkteaadmin/src/common/Constant.js
- hhtlmilkteaadmin/src/common/History.js
- hhtlmilkteaadmin/src/components/Spinner/index.jsx
- hhtlmilkteaadmin/src/index.js
- hhtlmilkteaadmin/src/services/SpinnerService.js
- hhtlmilkteaadmin/src/store/actions/SpinnerAction.js
- hhtlmilkteaadmin/src/store/index.js
- hhtlmilkteaadmin/src/store/reducers/SpinnerReducer.js
- hhtlmilkteaadmin/yarn.lock
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SpinnerController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/SpinnerRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/SpinnerResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/ISpinnerRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedSpinnersTable.java
> fix code, insert, delete

- hhtlmilkteaadmin/package.json
- hhtlmilkteaadmin/src/common/Constant.js
- hhtlmilkteaadmin/src/components/Spinner/index.jsx
> fix code, spinner

- hhtlmilkteaadmin/src/components/Spinner/index.jsx
> fix code, autocomplet

- hhtlmilkteaadmin/src/common/Constant.js
- hhtlmilkteaadmin/src/components/Spinner/index.jsx
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SpinnerController.java
> fix code, security

- hhtlmilkteauser/src/App.js
- hhtlmilkteauser/src/common/GoogleMap.jsx
- hhtlmilkteauser/src/common/ScrollOnTop.jsx
- hhtlmilkteauser/src/components/Home/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/SignUp/index.jsx
- hhtlmilkteauser/src/components/layout/Footer/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
> fix footer

- hhtlmilkteauser/src/components/Account/History/index.jsx
- hhtlmilkteauser/src/components/Account/Profile/index.jsx
- hhtlmilkteauser/src/components/Account/Voucher/index.jsx
- hhtlmilkteauser/src/components/layout/DefaultLayout.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
> fix template user

- hhtlmilkteauser/src/components/layout/Header/index.jsx
> fix code, header

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/UserController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/UserReponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/WishlistResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IWishlistRepository.java
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/UserService.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> wishlist response

- hhtlmilkteaadmin/src/components/Spinner/index.jsx
- hhtlmilkteaadmin/src/store/reducers/SpinnerReducer.js
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SpinnerController.java
> fix code spinner

- hhtlmilkteaadmin/src/App.js
- hhtlmilkteaadmin/src/components/Layout/ListItem/index.jsx
- hhtlmilkteaadmin/src/components/Product/AddProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/index.js
- hhtlmilkteaadmin/src/services/AddtionOptionService.js
- hhtlmilkteaadmin/src/services/CategoryService.js
- hhtlmilkteaadmin/src/services/ProductService.js
- hhtlmilkteaadmin/src/services/SizeOptionService.js
- hhtlmilkteaadmin/src/store/actions/AdditionOptionAction.js
- hhtlmilkteaadmin/src/store/actions/CategoryAction.js
- hhtlmilkteaadmin/src/store/actions/ProductAction.js
- hhtlmilkteaadmin/src/store/actions/SizeOptionAction.js
- hhtlmilkteaadmin/src/store/index.js
- hhtlmilkteaadmin/src/store/reducers/AdditionOptionReducer.js
- hhtlmilkteaadmin/src/store/reducers/CategoryReducer.js
- hhtlmilkteaadmin/src/store/reducers/ProductReducer.js
- hhtlmilkteaadmin/src/store/reducers/SizeOptionReducer.js
- hhtlmilkteaapi/pom.xml
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Product.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/ProductRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IProductRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedAddOptionsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedOrderDetailsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedProductsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedSaleOffsTable.java
- hhtlmilkteaapi/src/main/resources/application.properties
> product admin

- hhtlmilkteaadmin/package.json
- hhtlmilkteaadmin/src/App.js
- hhtlmilkteaadmin/src/components/Product/AddProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/DetailProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/EditProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/index.js
- hhtlmilkteaadmin/src/services/ProductService.js
- hhtlmilkteaadmin/src/store/actions/ProductAction.js
- hhtlmilkteaadmin/src/store/reducers/ProductReducer.js
- hhtlmilkteaadmin/yarn.lock
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
> product detail delete

- hhtlmilkteaadmin/package.json
- hhtlmilkteaadmin/src/common/APIClient.js
- hhtlmilkteaadmin/src/common/Constant.js
- hhtlmilkteaadmin/src/common/History.js
- hhtlmilkteaadmin/src/components/Layout/Navbar/index.jsx
- hhtlmilkteaadmin/src/components/Spinner/index.jsx
- hhtlmilkteaadmin/src/components/User/index.jsx
- hhtlmilkteaadmin/src/services/UserService.js
- hhtlmilkteaadmin/src/store/actions/UserAction.js
- hhtlmilkteaadmin/src/store/reducers/UserReducer.js
- hhtlmilkteaadmin/yarn.lock
- hhtlmilkteaapi/pom.xml
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/WebSocketConfig.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/TestController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/UserController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/UserRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IUserRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/security/service/CustomizeUserService.java
- hhtlmilkteauser/src/common/APIClient.js
- hhtlmilkteauser/src/common/History.js
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/index.js
fix code, user status, websocket
> fix code, user status, websocket

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/UserController.java
fix code, preauthorize admin user status
> fix code, preauthorize admin user status

- hhtlmilkteauser/src/common/GoogleMap.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
> fix header footer

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/UserController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/ProfileRequest.java
- hhtlmilkteauser/src/components/Account/Profile/index.jsx
- hhtlmilkteauser/src/services/UserService.js
- hhtlmilkteauser/src/store/actions/UserAction.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> user update profile

- hhtlmilkteauser/src/components/Account/Profile/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/store/actions/UserAction.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> fix profile + avatar

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IProductRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedCategoriesTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedProductsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedSizeOptionsTable.java
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Header/index.jsx
- hhtlmilkteauser/src/components/layout/Footer/index.jsx
- hhtlmilkteauser/src/services/CategoryService.js
- hhtlmilkteauser/src/store/actions/CategoryAction.js
- hhtlmilkteauser/src/store/index.js
- hhtlmilkteauser/src/store/reducers/CategoryReducer.js
- hhtlmilkteauser/yarn.lock
> product user

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
> fix product user

- hhtlmilkteauser/src/components/SignUp/index.jsx
> fix code, signup

- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/SignUp/index.jsx
> fix code, signup, signin

- hhtlmilkteauser/src/components/SignUp/index.jsx
> fix code, token

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/CategoryController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
- hhtlmilkteauser/src/services/CategoryService.js
> fix product

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IOrderRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedOrdersTable.java
- hhtlmilkteauser/package.json
- hhtlmilkteauser/src/components/Account/History/HistoryDetail/index.jsx
- hhtlmilkteauser/src/components/Account/History/index.jsx
- hhtlmilkteauser/src/components/TableHeader/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/HistoryService.js
- hhtlmilkteauser/src/store/actions/HistoryAction.js
- hhtlmilkteauser/src/store/index.js
- hhtlmilkteauser/src/store/reducers/HistoryReducer.js
- hhtlmilkteauser/yarn.lock
> add history user

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
> fix conflict

- README.md
> fix code, readme

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/OrderQuantityRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/CartResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IOrderRepository.java
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/services/OrderService.js
- hhtlmilkteauser/src/store/actions/OrderAction.js
- hhtlmilkteauser/src/store/reducers/OrderReducer.js
> shopping cart

- hhtlmilkteaadmin/src/App.js
- hhtlmilkteaadmin/src/components/Layout/ListItem/index.jsx
- hhtlmilkteaadmin/src/components/Order/DetailOrder/index.jsx
- hhtlmilkteaadmin/src/components/Order/index.jsx
- hhtlmilkteaadmin/src/services/OrderService.js
- hhtlmilkteaadmin/src/store/actions/OrderAction.js
- hhtlmilkteaadmin/src/store/index.js
- hhtlmilkteaadmin/src/store/reducers/OrderReducer.js
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/OrderStatusRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IOrderRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedOrderDetailsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedOrdersTable.java
- hhtlmilkteauser/package.json
- hhtlmilkteauser/src/App.js
- hhtlmilkteauser/src/components/Account/index.jsx
- hhtlmilkteauser/yarn.lock
add history detail + admin Order
> add history detail + admin Order

- hhtlmilkteaadmin/src/components/Product/AddProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/DetailProduct/index.jsx
- hhtlmilkteaadmin/src/components/Product/DetailProduct/report/index.jsx
- hhtlmilkteaadmin/src/components/Product/EditProduct/index.jsx
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/UserController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/WishListController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Wishlist.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/WishlistRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/WishlistResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IWishlistRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedWishlistsTable.java
- hhtlmilkteauser/src/App.js
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/components/Wishlist/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/WishlistService.js
- hhtlmilkteauser/src/store/actions/UserAction.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> wishlist page

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/WheelHistoryController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/WheelHistoryRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/WheelHistoryResponse.java
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
> fix code, wishlist

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SpinnerController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/WheelHistoryController.java
> fix code wheel

- README.md
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SpinnerController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/VoucherController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/WheelHistoryController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Code.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Voucher.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/VoucherRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/VoucherResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/ICodeRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IVoucherRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedCodesTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedSpinnersTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedVouchersTable.java
- hhtlmilkteauser/package.json
- hhtlmilkteauser/src/common/APIClient.js
- hhtlmilkteauser/src/components/Account/Voucher/index.jsx
- hhtlmilkteauser/src/components/Account/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/services/VoucherService.js
- hhtlmilkteauser/src/store/actions/VoucherAction.js
- hhtlmilkteauser/src/store/index.js
- hhtlmilkteauser/src/store/reducers/VoucherReducer.js
- hhtlmilkteauser/yarn.lock
> fix code, voucher

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/HhtlmilkteaapiApplication.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/Constant.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ShorterController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/GroupMember.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/GroupOrderDetails.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Order.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Product.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Shorter.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/UrlShorterRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/GroupOrderInfoResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/GroupOrderResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/UrlShorterResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupMemberRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupOrderDetailsRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IOrderRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IShorterRepository.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedGroupMemberTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedGroupOrderDetailsTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedOrdersTable.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/service/UrlShorterService.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/utility/Utils.java
- hhtlmilkteaapi/src/main/resources/application.properties
- hhtlmilkteauser/src/common/APIClient.js
fix code, url short, rest get data group order
> fix code, url short, rest get data group order

- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/components/layout/DefaultLayout.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
> view order group

- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
> sale off user

- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/PaymentForm/index.jsx
- hhtlmilkteauser/src/components/PrivateRoute/index.js
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/Wishlist/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/store/actions/AuthAction.js
- hhtlmilkteauser/src/store/reducers/AuthReducer.js
- hhtlmilkteauser/src/store/reducers/OrderReducer.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> fix security

- hhtlmilkteaapi/pom.xml
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/WebSocketConfig.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/TestController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/WSGroupOrderRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/GroupOrderInfoResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/GroupOrderResponse.java
- hhtlmilkteauser/package.json
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/AuthAction.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/index.js
- hhtlmilkteauser/src/store/reducers/GroupOrderReducer.js
- hhtlmilkteauser/yarn.lock
> fix code, show grouporder

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/WSGroupOrderRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupMemberRepository.java
- hhtlmilkteauser/public/index.html
- hhtlmilkteauser/src/common/APIClient.js
- hhtlmilkteauser/src/common/Constant.js
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/AuthAction.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/reducers/GroupOrderReducer.js
> fix code, ws show, share link

- hhtlmilkteaadmin/src/components/Order/DetailOrder/index.jsx
- hhtlmilkteaadmin/src/components/Order/index.jsx
- hhtlmilkteaadmin/src/store/reducers/OrderReducer.js
- hhtlmilkteauser/src/components/Account/index.jsx
> fix code order admin

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ProductController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/seed/SeedProductsTable.java
> change seed product data

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ShorterController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Order.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/response/GroupOrderInfoResponse.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupMemberRepository.java
- hhtlmilkteauser/src/components/Home/index.jsx
- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/AuthService.js
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/actions/OrderAction.js
> fix code, member, share link

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/HhtlmilkteaapiApplication.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/config/WebSocketConfig.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/GroupMemberRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupMemberRepository.java
- hhtlmilkteauser/src/components/CheckAddress/index.jsx
- hhtlmilkteauser/src/components/Dessert/Header/index.jsx
- hhtlmilkteauser/src/components/Forget/index.jsx
- hhtlmilkteauser/src/components/Home/index.jsx
- hhtlmilkteauser/src/components/Milktea/index.jsx
- hhtlmilkteauser/src/components/Page404/index.jsx
- hhtlmilkteauser/src/components/Product/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/SignUp/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
> fix code, fix support ws

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/GroupOrderDetails.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/payload/request/GroupMemberRequest.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IGroupOrderDetailsRepository.java
- hhtlmilkteauser/src/components/Home/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/actions/OrderAction.js
> fix code, +/-+

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/ShorterController.java
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Dessert/Header/index.jsx
- hhtlmilkteauser/src/components/Forget/index.jsx
- hhtlmilkteauser/src/components/Home/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/index.jsx
- hhtlmilkteauser/src/components/Page404/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/Product/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/SignUp/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/AuthService.js
- hhtlmilkteauser/src/services/GroupOrderService.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/reducers/UserReducer.js
> fix code, group order

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/AuthController.java
- hhtlmilkteauser/src/components/Account/index.jsx
- hhtlmilkteauser/src/components/CheckAddress/index.jsx
- hhtlmilkteauser/src/components/Dessert/Header/index.jsx
- hhtlmilkteauser/src/components/Milktea/index.jsx
- hhtlmilkteauser/src/components/Page404/index.jsx
- hhtlmilkteauser/src/components/PaymentForm/index.jsx
- hhtlmilkteauser/src/components/Product/index.jsx
- hhtlmilkteauser/src/components/ReturnMomo/index.jsx
- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/Wishlist/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/services/AuthService.js
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
- hhtlmilkteauser/src/store/reducers/GroupOrderReducer.js
- hhtlmilkteauser/src/store/reducers/OrderReducer.js
> fix code, group member

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/GroupOrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/repository/IShorterRepository.java
> fix code, shorter

- hhtlmilkteauser/src/components/Account/index.jsx
- hhtlmilkteauser/src/components/CheckAddress/index.jsx
- hhtlmilkteauser/src/components/Dessert/Content/index.jsx
- hhtlmilkteauser/src/components/Dessert/Header/index.jsx
- hhtlmilkteauser/src/components/Forget/index.jsx
- hhtlmilkteauser/src/components/Home/index.jsx
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
- hhtlmilkteauser/src/components/Milktea/index.jsx
- hhtlmilkteauser/src/components/Page404/index.jsx
- hhtlmilkteauser/src/components/PaymentForm/index.jsx
- hhtlmilkteauser/src/components/Product/Content/index.jsx
- hhtlmilkteauser/src/components/Product/index.jsx
- hhtlmilkteauser/src/components/ReturnMomo/index.jsx
- hhtlmilkteauser/src/components/ReturnVNPay/index.js
- hhtlmilkteauser/src/components/ShoppingCart/index.jsx
- hhtlmilkteauser/src/components/SignIn/index.jsx
- hhtlmilkteauser/src/components/SignUp/index.jsx
- hhtlmilkteauser/src/components/Spinner/index.jsx
- hhtlmilkteauser/src/components/Wishlist/index.jsx
- hhtlmilkteauser/src/components/layout/Header/index.jsx
- hhtlmilkteauser/src/store/actions/GroupOrderAction.js
> fix code, group order, ws

- hhtlmilkteaadmin/src/components/Category/DetailCategory/index.jsx
- hhtlmilkteaadmin/src/components/Layout/ListItem/index.jsx
- hhtlmilkteaadmin/src/components/Order/DetailOrder/index.jsx
- hhtlmilkteaadmin/src/components/Order/index.jsx
- hhtlmilkteaadmin/src/components/Product/DetailProduct/report/index.jsx
- hhtlmilkteaadmin/src/components/User/DetailUser/index.jsx
- hhtlmilkteaadmin/src/components/User/DetailUser/report/index.jsx
- hhtlmilkteauser/src/components/Account/History/index.jsx
> fix something

- hhtlmilkteaadmin/src/components/AdditionOption/index.jsx
- hhtlmilkteaadmin/src/components/Product/DetailProduct/report/index.jsx
- hhtlmilkteaadmin/src/components/SizeOption/index.jsx
- hhtlmilkteaadmin/src/components/User/DetailUser/report/index.jsx
- hhtlmilkteaadmin/src/store/reducers/AdditionOptionReducer.js
- hhtlmilkteaadmin/src/store/reducers/SizeOptionReducer.js
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/AddOptionController.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/SizeOptionController.java
> fix product, pdf

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/OrderController.java
> mark order update

- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Order.java
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/entity/Rating.java
> add rating

- hhtlmilkteaadmin/src/components/Spinner/index.jsx
- hhtlmilkteaadmin/src/components/User/DetailUser/index.jsx
- hhtlmilkteaadmin/src/components/User/DetailUser/report/index.jsx
- hhtlmilkteauser/src/components/Account/Profile/index.jsx
> fix code, admin, user

- hhtlmilkteaadmin/src/components/Category/index.jsx
- hhtlmilkteaapi/src/main/java/com/fpt/hhtlmilkteaapi/controller/VoucherController.java
- hhtlmilkteauser/src/components/Milktea/Content/index.jsx
fix code voucher, saleoff, category
> fix code voucher, saleoff, category
